In [21]:
import torch
from torch import optim
 
in_dim, out_dim = 5, 2
 
inputs = torch.randn(in_dim)
target = torch.tensor([1,2],dtype=torch.float32)
 
model = torch.nn.Linear(in_dim, out_dim, bias=True)
out = model(inputs)

In [22]:
inputs

tensor([ 0.7704,  0.0713,  1.5876, -0.2257,  1.0739])

In [23]:
target

tensor([1., 2.])

In [24]:
out

tensor([-0.4543,  0.4756], grad_fn=<AddBackward0>)

In [25]:
loss = torch.nn.CrossEntropyLoss()
computed_loss = loss(out, target)

In [26]:
for p in model.parameters():
    print(p.grad)

None
None


In [27]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4333,  0.4436,  0.1496,  0.2498, -0.2771],
         [-0.1476,  0.3907,  0.0680,  0.2371,  0.2327]], requires_grad=True),
 Parameter containing:
 tensor([-0.0356,  0.2571], requires_grad=True)]

In [28]:
computed_loss.backward()
 
for p in model.parameters():
    print(p.grad)
 

tensor([[-0.1164, -0.0108, -0.2400,  0.0341, -0.1623],
        [ 0.1164,  0.0108,  0.2400, -0.0341,  0.1623]])
tensor([-0.1512,  0.1512])
